# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'InstaCloneFirebase' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'FirebaseAnalytics'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  pod 'FirebaseStorage'
  pod 'FirebaseCore'
  pod 'Kingfisher'
  pod 'OneSignalXCFramework', '>= 3.0.0', '< 4.0'

end

target 'OneSignalNotificationServiceExtension' do
  use_frameworks!

  pod 'OneSignalXCFramework', '>= 3.0.0', '< 4.0'

end