# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SnapChatClone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SnapChatClone
  pod 'FirebaseAnalytics'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  pod 'FirebaseStorage'
  pod 'SDWebImage'
  pod 'ImageSlideshow', '~>1.8'
  pod 'ImageSlideshow/Kingfisher'

end
